### ISSUE TITLE
Cannot Import into UE4 - 12.5

### ISSUE THREAD

**Issue by soundyogi** [bw2012/UE4VoxelTerrain#1]
Hello,

I cannot import it properly. Is there a way to get it to work? :)  
Thanks!

**Comment by bw2012** [comment]
HI, 
I will check it today.

**Comment by soundyogi** [comment]
Thanks man! I have been trying but no luck. Its a shane they are making breaking changes with almost every release.

**Comment by bw2012** [comment]
Ok. I have migrated project to 4.12
You can check out last version

**Comment by soundyogi** [comment]
Hi!

I cloned the whole project and tried opening it in Unreal.

It tries to rebuild UE4VoxelTerrain and fails. Telling me to compile manually.
(I am sorry I am new to Unreal, am I missing something obvious?)
Could you tell me your approach?

Thanks many times!

**Comment by bw2012** [comment]
Could you please look at folder UE4VoxelTerrain/Plugins/UnrealSandboxTerrain. Is it empty or not?

**Comment by soundyogi** [comment]
Of Course. The subgit was not there.
Did I use a wrong command? (git clone, git submodule update -- recursive)
but:
I cloned it manualy and now it is working!
https://cdn.pastemagazine.com/www/system/images/photo_albums/archer-memes-/large/archer-meme-10.jpg?1384968217

**Comment by soundyogi** [comment]
Since it works now on 12.5 closed!
(still interested in what I did wrong though :D )
