### ISSUE TITLE
TerrainProject

### ISSUE THREAD

**Issue by SvarogZ** [bw2012/UE4VoxelTerrain#13]
Important issue.

**Comment by bw2012** [comment]
К сожалению, сейчас нет технической возможности использовать скайп.
Если у вас есть какие-то вопросы или предложения, пожалуйста, пишите на **unrealsandbox@gmail.com**

**Comment by SvarogZ** [comment]
Написал. Прошу дать ответ. Каким бы он ни был :)

**Comment by bw2012** [comment]
Спасибо. Я написал ответ на почту.
