### ISSUE TITLE
Height map generation and terrain painting

### ISSUE THREAD

**Issue by JasonWeise** [bw2012/UE4VoxelTerrain#16]
Hi

I am trialing this solution for editable terrain in an upcoming title I am considering and think it is great so far. Only question is whether there is a way to generate the terrain off a heightmap (or convert a UE Landscape) and whether I can paint the terrain so I can have different areas like, grass, mud, rock etc..

Thanks in advance.

**Comment by bw2012** [comment]
Hi
Sorry, but don't understand the problem. Do you mean how can convert ue4 embedded heightmap-terrain to voxel terrain? This feature will implement in future releases.
