### ISSUE TITLE
Doesn't seem to open with 12.5...

### ISSUE THREAD

**Issue by noobularkid** [bw2012/UE4VoxelTerrain#2]
It wants me to attempt to rebuild some files manually from the source, but it's not building the files to be able to do so in the first place...

**Comment by bw2012** [comment]
Hi!
Could you please check folder {Project}/Plugins/UnrealSandboxTerrain? Is it empty or not?

**Comment by noobularkid** [comment]
It's empty, what did I manage to do wrong lol

**Comment by bw2012** [comment]
please, clone repo with --recursive option
like: git clone --recursive https://github.com/bw2012/UE4VoxelTerrain.git

**Comment by noobularkid** [comment]
is it required to rebuild the source manually, or is something wrong on my
end, the unrealsandbox.dll and voxelterrain.dll modules are missing.

**Comment by bw2012** [comment]
Sorry but I have migrated project to 13.1 
12.5 does not support anymore. Please try to open project with UnrealEngine 4.13.1

Also  I have prepared archive with project (if you still have problems with cloning repo and building sources)
bit.ly/2eP5GtU

If you need version for 12.5 then I can prepare special downgraded version for you.
