### ISSUE TITLE
Run problem on 4.13.1

### ISSUE THREAD

**Issue by funkish** [bw2012/UE4VoxelTerrain#3]
Run on 4.13.1 have warning then missing UE4VoxeTerrain modules.
UE4Editor-EU4VoxelTerrain.dll
UE4Editor-UnrealSandboxTerrain.dll
Would you like to rebuild then now?

On click "Yes" project rebuilding and appearing Error: UE4VoxelTerrain could not be compiled. Try rebuilding from source manually.

**Comment by bw2012** [comment]
Could you please check folder {Project}/Plugins/UnrealSandboxTerrain? Is it empty or not?

**Comment by funkish** [comment]
Folder is full.

<Binaries>
<Intermediate>
<Resources>
<Source>
.git
.gitignore
README.md
UnrealSandboxTerrain.uplugin

**Comment by bw2012** [comment]
Windows or MacOS?

**Comment by funkish** [comment]
Sorry for wasted you time, this is my bad. The problem was not in you code.
I have new one, in this time You has note // TODO: check controller and not implemented function ASandboxTerrainController::GetZoneInstance(Hit.Actor.Get());

**Comment by bw2012** [comment]
It looks like you have not old version of project. Could you please check out last changes?

**Comment by funkish** [comment]
I used your advice and the problem was solved. Thank you!
