### ISSUE TITLE
Unable to open with 4.14.0

### ISSUE THREAD

**Issue by Nique** [bw2012/UE4VoxelTerrain#4]
Just saying: unable to open with 4.14.0 :)

The UnrealSandboxTerrain directory is populated.

[Screenshot](http://image.prntscr.com/image/38ff7eb04bf149de8685bf93e65a5cc4.png)

**Comment by bw2012** [comment]
Hi! 
It looks like problem on UE 4.14.0 side. The module was compiled successfully but not loaded by unknown reason. 
I have found same problem in answer hub
https://answers.unrealengine.com/questions/527415/c-plugin-module-failed-to-load.html

I will try to find solution

**Comment by bw2012** [comment]
Fixed
I have pushed fix to the master branch

Please update your repository
