### ISSUE TITLE
Missing UE4VoxelTerrain Modules

### ISSUE THREAD

**Issue by Mitwirker** [bw2012/UE4VoxelTerrain#5]
Im trying to open with 4.14.1 and i get:

Missing UE4VoxelTerrain Modules
The following modules are missing or built with a different engine version:
UE4Editor-UE4VoxelTerrain.dll
Would you like to rebuild them now?

After pressing yes it is starting to build and the that appears:

Error
UE4VoxelTerrain could not be compiled. Try rebuilding from source manually.

btw the fodler in the Plugins folder are both empty.

**Comment by bw2012** [comment]
> btw the fodler in the Plugins folder are both empty.

It looks like project was cloned without submodules. 
Please use command line `git clone --recursive https://github.com/bw2012/UE4VoxelTerrain.git`

**Comment by Mitwirker** [comment]
I downloaded the Plugins and pastet it. I did not know that I can download them separately.
And I have an another problem now if I change the Zone Grid Dimension in the Terrain Controller and press play UE crashes but at 64 it works fine.

**Comment by bw2012** [comment]
Unfortunately the parameter "Zone Grid Dimension" is temporarily not supported in last releases. I have removed this field from editor. Now it always fixed to 64.
