### ISSUE TITLE
Adding new ground level materials

### ISSUE THREAD

**Issue by YegorDia** [bw2012/UE4VoxelTerrain#6]
As I reviewed the code ther eis only 1 material which is as asset used to be grass+dirt and it is separated by lerp, but. I am not sure how it is possible to add new materials and stuff, because as I see in SandBoxVoxelGenerator it is making unsigned chars as material and I am pretty confused, cus I dont knwo how the complete system works, could you explain in few words what is the best way to do it? thank you

**Comment by bw2012** [comment]
Unfortunately this part is still not finished yet.
I have planned multi-material terrain therefore `unsigned short` is used as material id but at this time I have temporary implemented only two material (dirt / grass) as tech demo.
In next releases I will refactor method `void materialCalculation(struct TmpPoint& tp, Point point1, Point point2)` for implement multi-material functionality.

Sorry for messy code I will fix it in future.

If you want to change dirt texture you can just change existing triplanar material.

**Comment by YegorDia** [comment]
Thank you! So if I would find a good way to implement multi material stuff I will fork and make pull request to maybe make it happen faster ;)
