### ISSUE TITLE
Compilation errors

### ISSUE THREAD

**Issue by davidg0** [bw2012/UE4VoxelTerrain#7]
Running Mono...

Setting up Mono
/Users/Shared/UnrealEngine/4.14/Engine /Users/Shared/UnrealEngine/4.14/Engine/Binaries/Mac
Compiling with MacOSX SDK 10.11
@progress push 5%
Parsing headers for UE4VoxelTerrainEditor
  Running UnrealHeaderTool "/Users/DAVID/UE4VoxelTerrain/UE4VoxelTerrain/UE4VoxelTerrain.uproject" "/Users/DAVID/UE4VoxelTerrain/UE4VoxelTerrain/Intermediate/Build/Mac/UE4VoxelTerrainEditor/Development/UE4VoxelTerrainEditor.uhtmanifest" -LogCmds="loginit warning, logexit warning, logdatabase error" -Unattended -WarningsAsErrors -installed
Reflection code generated for UE4VoxelTerrainEditor in 6.205086 seconds
@progress pop
Performing 16 actions (4 in parallel)
[4/16] Compile Module.UnrealSandboxTerrain.cpp
[2/16] Compile Module.UnrealSandboxToolkit.cpp
[1/16] Compile UE4VoxelTerrain.h
[3/16] Compile UnrealSandboxToolkit.generated.cpp
[5/16] Compile UnrealSandboxTerrain.generated.cpp
In file included from /Users/DAVID/UE4VoxelTerrain/UE4VoxelTerrain/Plugins/UnrealSandboxToolkit/Intermediate/Build/Mac/UE4Editor/Development/UnrealSandboxToolkit/Module.UnrealSandboxToolkit.cpp:3:
/Users/DAVID/UE4VoxelTerrain/UE4VoxelTerrain/Plugins/UnrealSandboxToolkit/Source/UnrealSandboxToolkit/Private/ContainerComponent.cpp:13:2: warning: 'bWantsBeginPlay' is deprecated: bWantsBeginPlay was inconsistently enforced and is now unused Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile. [-Wdeprecated-declarations]
        bWantsBeginPlay = true;
        ^
Runtime/Engine/Classes/Components/ActorComponent.h:193:9: note: 'bWantsBeginPlay' has been explicitly marked deprecated here
        uint32 bWantsBeginPlay:1;
               ^
In file included from /Users/DAVID/UE4VoxelTerrain/UE4VoxelTerrain/Plugins/UnrealSandboxToolkit/Intermediate/Build/Mac/UE4Editor/Development/UnrealSandboxToolkit/Module.UnrealSandboxToolkit.cpp:4:
/Users/DAVID/UE4VoxelTerrain/UE4VoxelTerrain/Plugins/UnrealSandboxToolkit/Source/UnrealSandboxToolkit/Private/SandboxCharacter.cpp:17:14: warning: 'AttachTo' is deprecated: This function is deprecated, please use AttachToComponent instead. Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile. [-Wdeprecated-declarations]
        CameraBoom->AttachTo(RootComponent);
                    ^
Runtime/Engine/Classes/Components/SceneComponent.h:606:7: note: 'AttachTo' has been explicitly marked deprecated here
        bool AttachTo(USceneComponent* InParent, FName InSocketName = NAME_None, EAttachLocation::Type AttachType = EAttachLocation::KeepRelativeOffset, bool bWeldSimulatedBodies = false);
             ^
In file included from /Users/DAVID/UE4VoxelTerrain/UE4VoxelTerrain/Plugins/UnrealSandboxToolkit/Intermediate/Build/Mac/UE4Editor/Development/UnrealSandboxToolkit/Module.UnrealSandboxToolkit.cpp:4:
/Users/DAVID/UE4VoxelTerrain/UE4VoxelTerrain/Plugins/UnrealSandboxToolkit/Source/UnrealSandboxToolkit/Private/SandboxCharacter.cpp:20:16: warning: 'AttachTo' is deprecated: This function is deprecated, please use AttachToComponent instead. Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile. [-Wdeprecated-declarations]
        FollowCamera->AttachTo(CameraBoom, USpringArmComponent::SocketName); // Attach the camera to the end of the boom and let the boom adjust to match the controller orientation
                      ^
Runtime/Engine/Classes/Components/SceneComponent.h:606:7: note: 'AttachTo' has been explicitly marked deprecated here
        bool AttachTo(USceneComponent* InParent, FName InSocketName = NAME_None, EAttachLocation::Type AttachType = EAttachLocation::KeepRelativeOffset, bool bWeldSimulatedBodies = false);
             ^
In file included from /Users/DAVID/UE4VoxelTerrain/UE4VoxelTerrain/Plugins/UnrealSandboxToolkit/Intermediate/Build/Mac/UE4Editor/Development/UnrealSandboxToolkit/Module.UnrealSandboxToolkit.cpp:4:
/Users/DAVID/UE4VoxelTerrain/UE4VoxelTerrain/Plugins/UnrealSandboxToolkit/Source/UnrealSandboxToolkit/Private/SandboxCharacter.cpp:348:14: warning: 'AttachTo' is deprecated: This function is deprecated, please use AttachToComponent instead. Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile. [-Wdeprecated-declarations]
                GetMesh()->AttachTo(GetCapsuleComponent(), NAME_None, EAttachLocation::SnapToTargetIncludingScale);
                           ^
Runtime/Engine/Classes/Components/SceneComponent.h:606:7: note: 'AttachTo' has been explicitly marked deprecated here
        bool AttachTo(USceneComponent* InParent, FName InSocketName = NAME_None, EAttachLocation::Type AttachType = EAttachLocation::KeepRelativeOffset, bool bWeldSimulatedBodies = false);
             ^
In file included from /Users/DAVID/UE4VoxelTerrain/UE4VoxelTerrain/Plugins/UnrealSandboxToolkit/Intermediate/Build/Mac/UE4Editor/Development/UnrealSandboxToolkit/Module.UnrealSandboxToolkit.cpp:5:
/Users/DAVID/UE4VoxelTerrain/UE4VoxelTerrain/Plugins/UnrealSandboxToolkit/Source/UnrealSandboxToolkit/Private/SandboxEnvironment.cpp:144:2: error: use of undeclared identifier 'gmtime_s'; did you mean 'gmtime_r'?
        gmtime_s(&ptm, &rawtime);
        ^~~~~~~~
        gmtime_r
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include/time.h:125:12: note: 'gmtime_r' declared here
struct tm *gmtime_r(const time_t * __restrict, struct tm * __restrict);
           ^
In file included from /Users/DAVID/UE4VoxelTerrain/UE4VoxelTerrain/Plugins/UnrealSandboxToolkit/Intermediate/Build/Mac/UE4Editor/Development/UnrealSandboxToolkit/Module.UnrealSandboxToolkit.cpp:5:
/Users/DAVID/UE4VoxelTerrain/UE4VoxelTerrain/Plugins/UnrealSandboxToolkit/Source/UnrealSandboxToolkit/Private/SandboxEnvironment.cpp:144:11: error: cannot initialize a parameter of type 'const time_t *' (aka 'const long *') with an rvalue of type 'tm *'
        gmtime_s(&ptm, &rawtime);
                 ^~~~
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include/time.h:125:46: note: passing argument to parameter here
struct tm *gmtime_r(const time_t * __restrict, struct tm * __restrict);
                                             ^
In file included from /Users/DAVID/UE4VoxelTerrain/UE4VoxelTerrain/Plugins/UnrealSandboxTerrain/Intermediate/Build/Mac/UE4Editor/Development/UnrealSandboxTerrain/Module.UnrealSandboxTerrain.cpp:5:
In file included from /Users/DAVID/UE4VoxelTerrain/UE4VoxelTerrain/Plugins/UnrealSandboxTerrain/Source/UnrealSandboxTerrain/Private/SandboxTerrainController.cpp:4:
In file included from ../../../../../DAVID/UE4VoxelTerrain/UE4VoxelTerrain/Plugins/UnrealSandboxTerrain/Source/UnrealSandboxTerrain/Public/TerrainZoneComponent.h:6:
/Users/DAVID/UE4VoxelTerrain/UE4VoxelTerrain/Plugins/UnrealSandboxTerrain/Source/UnrealSandboxTerrain/Private/SandboxTerrainMeshComponent.h:26:23: warning: declaration shadows a field of 'USandboxTerrainMeshComponent' [-Wshadow]
        void SetLodFlag(bool bLodFlag) {
                             ^
/Users/DAVID/UE4VoxelTerrain/UE4VoxelTerrain/Plugins/UnrealSandboxTerrain/Source/UnrealSandboxTerrain/Private/SandboxTerrainMeshComponent.h:43:7: note: previous declaration is here
        bool bLodFlag;
             ^
In file included from /Users/DAVID/UE4VoxelTerrain/UE4VoxelTerrain/Plugins/UnrealSandboxTerrain/Intermediate/Build/Mac/UE4Editor/Development/UnrealSandboxTerrain/Module.UnrealSandboxTerrain.cpp:5:
/Users/DAVID/UE4VoxelTerrain/UE4VoxelTerrain/Plugins/UnrealSandboxTerrain/Source/UnrealSandboxTerrain/Private/SandboxTerrainController.cpp:311:18: warning: 'AttachTo' is deprecated: This function is deprecated, please use AttachToComponent instead. Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile. [-Wdeprecated-declarations]
                ZoneComponent->AttachTo(RegionComponent);
                               ^
Runtime/Engine/Classes/Components/SceneComponent.h:606:7: note: 'AttachTo' has been explicitly marked deprecated here
        bool AttachTo(USceneComponent* InParent, FName InSocketName = NAME_None, EAttachLocation::Type AttachType = EAttachLocation::KeepRelativeOffset, bool bWeldSimulatedBodies = false);
             ^
In file included from /Users/DAVID/UE4VoxelTerrain/UE4VoxelTerrain/Plugins/UnrealSandboxTerrain/Intermediate/Build/Mac/UE4Editor/Development/UnrealSandboxTerrain/Module.UnrealSandboxTerrain.cpp:5:
/Users/DAVID/UE4VoxelTerrain/UE4VoxelTerrain/Plugins/UnrealSandboxTerrain/Source/UnrealSandboxTerrain/Private/SandboxTerrainController.cpp:317:20: warning: 'AttachTo' is deprecated: This function is deprecated, please use AttachToComponent instead. Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile. [-Wdeprecated-declarations]
                TerrainMeshComp->AttachTo(ZoneComponent);
                                 ^
Runtime/Engine/Classes/Components/SceneComponent.h:606:7: note: 'AttachTo' has been explicitly marked deprecated here
        bool AttachTo(USceneComponent* InParent, FName InSocketName = NAME_None, EAttachLocation::Type AttachType = EAttachLocation::KeepRelativeOffset, bool bWeldSimulatedBodies = false);
             ^
In file included from /Users/DAVID/UE4VoxelTerrain/UE4VoxelTerrain/Plugins/UnrealSandboxTerrain/Intermediate/Build/Mac/UE4Editor/Development/UnrealSandboxTerrain/Module.UnrealSandboxTerrain.cpp:5:
/Users/DAVID/UE4VoxelTerrain/UE4VoxelTerrain/Plugins/UnrealSandboxTerrain/Source/UnrealSandboxTerrain/Private/SandboxTerrainController.cpp:325:22: warning: 'AttachTo' is deprecated: This function is deprecated, please use AttachToComponent instead. Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile. [-Wdeprecated-declarations]
                CollisionMeshComp->AttachTo(ZoneComponent);
                                   ^
Runtime/Engine/Classes/Components/SceneComponent.h:606:7: note: 'AttachTo' has been explicitly marked deprecated here
        bool AttachTo(USceneComponent* InParent, FName InSocketName = NAME_None, EAttachLocation::Type AttachType = EAttachLocation::KeepRelativeOffset, bool bWeldSimulatedBodies = false);
             ^
In file included from /Users/DAVID/UE4VoxelTerrain/UE4VoxelTerrain/Plugins/UnrealSandboxTerrain/Intermediate/Build/Mac/UE4Editor/Development/UnrealSandboxTerrain/Module.UnrealSandboxTerrain.cpp:5:
/Users/DAVID/UE4VoxelTerrain/UE4VoxelTerrain/Plugins/UnrealSandboxTerrain/Source/UnrealSandboxTerrain/Private/SandboxTerrainController.cpp:359:65: warning: declaration shadows a local variable [-Wshadow]
                bool operator()(VoxelData* vd, FVector v, float radius, float strength) {
                                                                              ^
/Users/DAVID/UE4VoxelTerrain/UE4VoxelTerrain/Plugins/UnrealSandboxTerrain/Source/UnrealSandboxTerrain/Private/SandboxTerrainController.cpp:353:84: note: previous declaration is here
void ASandboxTerrainController::digTerrainRoundHole(FVector origin, float r, float strength) {
                                                                                   ^
/Users/DAVID/UE4VoxelTerrain/UE4VoxelTerrain/Plugins/UnrealSandboxTerrain/Source/UnrealSandboxTerrain/Private/SandboxTerrainController.cpp:402:65: warning: declaration shadows a local variable [-Wshadow]
                bool operator()(VoxelData* vd, FVector v, float radius, float strength) {
                                                                              ^
/Users/DAVID/UE4VoxelTerrain/UE4VoxelTerrain/Plugins/UnrealSandboxTerrain/Source/UnrealSandboxTerrain/Private/SandboxTerrainController.cpp:396:83: note: previous declaration is here
void ASandboxTerrainController::digTerrainCubeHole(FVector origin, float r, float strength) {
                                                                                  ^
In file included from /Users/DAVID/UE4VoxelTerrain/UE4VoxelTerrain/Plugins/UnrealSandboxTerrain/Intermediate/Build/Mac/UE4Editor/Development/UnrealSandboxTerrain/Module.UnrealSandboxTerrain.cpp:6:
/Users/DAVID/UE4VoxelTerrain/UE4VoxelTerrain/Plugins/UnrealSandboxTerrain/Source/UnrealSandboxTerrain/Private/SandboxTerrainMeshComponent.cpp:208:26: warning: declaration shadows a local variable [-Wshadow]
                                                        FProcMeshSection& SrcTransitionSection = Component->ProcMeshSections[SectionIdx].transitionMeshArray[i];
                                                                          ^
/Users/DAVID/UE4VoxelTerrain/UE4VoxelTerrain/Plugins/UnrealSandboxTerrain/Source/UnrealSandboxTerrain/Private/SandboxTerrainMeshComponent.cpp:206:24: note: previous declaration is here
                                        FProcMeshSection& SrcTransitionSection = Component->ProcMeshSections[SectionIdx].transitionMeshArray[0];
                                                          ^
In file included from /Users/DAVID/UE4VoxelTerrain/UE4VoxelTerrain/Plugins/UnrealSandboxTerrain/Intermediate/Build/Mac/UE4Editor/Development/UnrealSandboxTerrain/Module.UnrealSandboxTerrain.cpp:7:
/Users/DAVID/UE4VoxelTerrain/UE4VoxelTerrain/Plugins/UnrealSandboxTerrain/Source/UnrealSandboxTerrain/Private/SandboxVoxeldata.cpp:405:61: warning: field 'extractor' will be initialized after field 'meshSection' [-Wreorder]
                MeshHandler(VoxelMeshExtractor* e, FProcMeshSection* s) : extractor(e), meshSection(s) { }
                                                                          ^
In file included from /Users/DAVID/UE4VoxelTerrain/UE4VoxelTerrain/Plugins/UnrealSandboxTerrain/Intermediate/Build/Mac/UE4Editor/Development/UnrealSandboxTerrain/Module.UnrealSandboxTerrain.cpp:10:
/Users/DAVID/UE4VoxelTerrain/UE4VoxelTerrain/Plugins/UnrealSandboxTerrain/Source/UnrealSandboxTerrain/Private/TerrainZoneComponent.cpp:284:33: warning: 'AttachTo' is deprecated: This function is deprecated, please use AttachToComponent instead. Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile. [-Wdeprecated-declarations]
                InstancedStaticMeshComponent->AttachTo(this);
                                              ^
Runtime/Engine/Classes/Components/SceneComponent.h:606:7: note: 'AttachTo' has been explicitly marked deprecated here
        bool AttachTo(USceneComponent* InParent, FName InSocketName = NAME_None, EAttachLocation::Type AttachType = EAttachLocation::KeepRelativeOffset, bool bWeldSimulatedBodies = false);
             ^
In file included from /Users/DAVID/UE4VoxelTerrain/UE4VoxelTerrain/Plugins/UnrealSandboxTerrain/Intermediate/Build/Mac/UE4Editor/Inc/UnrealSandboxTerrain/UnrealSandboxTerrain.generated.cpp:10:
In file included from ../../../../../DAVID/UE4VoxelTerrain/UE4VoxelTerrain/Plugins/UnrealSandboxTerrain/Intermediate/Build/Mac/UE4Editor/Inc/UnrealSandboxTerrain/UnrealSandboxTerrain.generated.dep.h:15:
../../../../../DAVID/UE4VoxelTerrain/UE4VoxelTerrain/Plugins/UnrealSandboxTerrain/Source/UnrealSandboxTerrain/Private/SandboxTerrainMeshComponent.h:26:23: warning: declaration shadows a field of 'USandboxTerrainMeshComponent' [-Wshadow]
        void SetLodFlag(bool bLodFlag) {
                             ^
../../../../../DAVID/UE4VoxelTerrain/UE4VoxelTerrain/Plugins/UnrealSandboxTerrain/Source/UnrealSandboxTerrain/Private/SandboxTerrainMeshComponent.h:43:7: note: previous declaration is here
        bool bLodFlag;
             ^
4 warnings and 2 errors generated.
[6/16] Compile UE4VoxelTerrain.generated.cpp
1 warning generated.
[7/16] Compile MainHUD.cpp
[8/16] Compile SystemInfoWidget.cpp
[9/16] Compile UE4VoxelTerrainGameMode.cpp
[10/16] Compile UE4VoxelTerrainCharacter.cpp
[11/16] Compile UE4VoxelTerrainPlayerController.cpp
/Users/DAVID/UE4VoxelTerrain/UE4VoxelTerrain/Source/UE4VoxelTerrain/UE4VoxelTerrainPlayerController.cpp:57:13: error: no member named 'round' in namespace 'std'; did you mean simply 'round'?
                                Tmp.Set(std::round(Tmp.X), std::round(Tmp.Y), std::round(Tmp.Z));
                                        ^~~~~~~~~~
                                        round
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include/math.h:490:15: note: 'round' declared here
extern double round(double);
              ^
/Users/DAVID/UE4VoxelTerrain/UE4VoxelTerrain/Source/UE4VoxelTerrain/UE4VoxelTerrainPlayerController.cpp:57:32: error: no member named 'round' in namespace 'std'; did you mean simply 'round'?
                                Tmp.Set(std::round(Tmp.X), std::round(Tmp.Y), std::round(Tmp.Z));
                                                           ^~~~~~~~~~
                                                           round
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include/math.h:490:15: note: 'round' declared here
extern double round(double);
              ^
/Users/DAVID/UE4VoxelTerrain/UE4VoxelTerrain/Source/UE4VoxelTerrain/UE4VoxelTerrainPlayerController.cpp:57:51: error: no member named 'round' in namespace 'std'; did you mean simply 'round'?
                                Tmp.Set(std::round(Tmp.X), std::round(Tmp.Y), std::round(Tmp.Z));
                                                                              ^~~~~~~~~~
                                                                              round
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include/math.h:490:15: note: 'round' declared here
extern double round(double);
              ^

**Comment by davidg0** [comment]
I was trying to open the project by 4.14.3

**Comment by davidg0** [comment]
Everything was downloaded through the git command

**Comment by davidg0** [comment]
gmtime_s was identified as an undeclared item, and xcode suggested gmtime_r

**Comment by bw2012** [comment]
Did you change source code to solve this issue? Could you please create pull request? I have not Mac OS at this moment and I cannot check this bug properly

**Comment by davidg0** [comment]
It is because of some improper c++ settings of the osx sdk. To solve the problem, just simply delete the "std::" class identification before round.
